# -*- coding: utf-8 -*-
"""sentiment-analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p1rTsevRNvq1Nu0asXRg2Oc4_-NME7XX
"""

import pandas as pd
import glob
import re

# load dataset

csv_files = glob.glob("/content/*.csv")

all_data = pd.concat([pd.read_csv(f) for f in csv_files], ignore_index=True)

print("Total rows:", len(all_data))
all_data.head()

all_data=all_data.dropna(subset=['textDisplay'])


def cleaning(text):
    text = text.lower()                                  # lowercase
    text = re.sub(r"http\S+", " ", text)                 # remove links
    text = re.sub(r"@\w+", " ", text)                    # remove @username
    text = re.sub(r"[^a-zA-Z0-9\s]", " ", text)          # remove symbols & emoji
    text = re.sub(r"\s+", " ", text).strip()             # remove extra spaces
    return text

all_data['clean_text'] = all_data['textDisplay'].apply(cleaning)

all_data.head()

import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('punkt_tab')

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess(text):
    tokens = word_tokenize(text)
    tokens = [t for t in tokens if t not in stop_words]           # remove stopwords
    tokens = [lemmatizer.lemmatize(t) for t in tokens]            # lemmatize
    return " ".join(tokens)

all_data['prep_text'] = all_data['clean_text'].apply(preprocess)

from textblob import TextBlob

def get_sentiment(text):
    polarity = TextBlob(text).sentiment.polarity
    if polarity > 0:
        return "positive"
    elif polarity < 0:
        return "negative"
    else:
        return "neutral"

all_data['sentiment'] = all_data['prep_text'].apply(get_sentiment)

all_data['sentiment'].value_counts()

print(all_data.columns)
print(all_data['sentiment'].value_counts())
print("Total rows:", len(all_data))

# split data
from sklearn.model_selection import train_test_split

X = all_data['prep_text']        # fitur teks
y = all_data['sentiment']        # label sentimen

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,               # 80% train, 20% test
    random_state=42,
    stratify=y                   # supaya proporsi label seimbang
)

print("Train size:", len(X_train))
print("Test size :", len(X_test))

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    ngram_range=(1,2),      # unigram + bigram
    min_df=2,               # kata muncul minimal di 2 dokumen
    max_df=0.95             # buang kata yang terlalu sering muncul
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf  = tfidf.transform(X_test)

X_train_tfidf.shape, X_test_tfidf.shape

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

nb_model = MultinomialNB()
nb_model.fit(X_train_tfidf, y_train)

y_pred_nb = nb_model.predict(X_test_tfidf)

print("=== Naive Bayes Performance ===")
print("Accuracy:", accuracy_score(y_test, y_pred_nb))
print("\nClassification Report:\n", classification_report(y_test, y_pred_nb))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_nb))

from sklearn.linear_model import LogisticRegression

logreg_model = LogisticRegression(
    max_iter=1000,
    n_jobs=-1
)
logreg_model.fit(X_train_tfidf, y_train)

y_pred_lr = logreg_model.predict(X_test_tfidf)

print("=== Logistic Regression Performance ===")
print("Accuracy:", accuracy_score(y_test, y_pred_lr))
print("\nClassification Report:\n", classification_report(y_test, y_pred_lr))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_lr))

# gunakan seluruh data
X_all_tfidf = tfidf.transform(all_data['prep_text'])

all_data['pred_sentiment'] = nb_model.predict(X_all_tfidf)

print(all_data['pred_sentiment'].value_counts())